services:
  bot:
    # entrypoint: bash
    build: .
    networks:
      internal:
      external:
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.18
    networks:
      - internal
    environment:
      MYSQL_DATABASE: wayback
      MYSQL_USER: wayback
      MYSQL_PASSWORD: 1234abcd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-data:/var/lib/mysql
networks:
  external:
  internal:
    internal: true
